apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-lecioalves-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
  # need to point to pv, already created for namespace, this suggest the format
  volumeName: project2-pv-lecioalves
---
apiVersion: v1
kind: Pod
metadata:
  name: playlist-recomender-shared-folder
spec:
  containers:
  - name: ml-recomender
    image: lcharles060/ml-recomender-service:0.1
    # does not work with block devices
#    volumeDevices:
#      - name: pvc-block-device
#        devicePath: /dev/xvdb
    volumeMounts:
    - name: shared-folder
      mountPath: "/shared"
